import React from 'react'

function index() {
    return (
        <div>
            <footer>
                <h6 style={fontStyle}>© Copyright (Generated by REACT.JS) </h6>
            </footer>
        </div>
    )
}

const fontStyle = {
    fontSize: '0.75rem'
}

export default index
